# Generated by Django 5.1.3 on 2025-11-01 04:38

from django.db import migrations

def full_roles(apps, schema_editor):
    role = apps.get_model('role', 'Role')
    role.objects.create(name='DIRECTOR', description='Role de Director de la escuela, quién podra gestionar usuarios internos, clientes y matrículas')
    role.objects.create(name='ADMIN', description='Role de Administrador, quién podrá gestionar clientes y matrículas')
    role.objects.create(name='CLIENT', description='Role de Cliente, quién podrá ver y gestionar sus propias matrículas')
    role.objects.create(name='TRAINER', description='Role de Entrenador, quién podrá ver y gestionar las asistencias y cursos')

class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(full_roles),
    ]
