# Generated by Django 5.1.3 on 2025-11-02 20:44

from django.db import migrations
from plan.models import Plan


def full_plans(apps, schema_editor):
    plan = apps.get_model('plan', 'Plan')

    durations = [
        ('Mensual', 30, 1),
        ('Bimestral', 60, 2),
        ('Trimestral', 90, 3),
        ('Semestral', 180, 6),
        ('Anual', 365, 12),
    ]

    transport_types = [
        ('Completo', 1, 0, 'servicio de recogida en la casa y entrega.'),
        ('Solo Mañana', 2, -5000, 'solo servicio de recogida en la mañana.'),
        ('Solo Tarde', 3, -5000, 'solo servicio de entrega en la tarde.'),
        ('Sin Transporte', 4, -10000, 'sin servicio de transporte.'),
    ]

    base_price = 60000

    for duration_name, duration_days, multiplier in durations:
        for transport_name, transport_type, adjustment, transport_desc in transport_types:
            price = base_price * multiplier + adjustment
            if price < 0:
                price = 0

            name = f"Matrícula {duration_name} con Transporte {transport_name}"
            description = (
                f"Plan de matrícula {duration_name.lower()} a la escuela canina con {transport_desc}"
            )

            Plan.objects.create(
                name=name,
                description=description,
                duration_days=duration_days,
                transport_type=transport_type,
                price=price
            )


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(full_plans),
    ]
